#! /bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24
PANEL_FONT="Inconsolata-10"
PANEL_ICON_FONT="FontAwesome-10"
PANEL_WM_NAME=bspwm_panel
export PANEL_FIFO PANEL_HEIGHT PANEL_FONT PANEL_WM_NAME

SCRIPTS_DIR=$(dirname "$0")/scripts

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT

bspc subscribe report > "$PANEL_FIFO" &

. $SCRIPTS_DIR/title.sh > "$PANEL_FIFO" &
. $SCRIPTS_DIR/clock.sh > "$PANEL_FIFO" &
. $SCRIPTS_DIR/calendar.sh > "$PANEL_FIFO" &
. $SCRIPTS_DIR/shortcuts.sh > "$PANEL_FIFO" &

# battery
while true;
do
  . $SCRIPTS_DIR/battery.sh
  sleep 5;
done > "$PANEL_FIFO" &

# alsa volume
while true;
do
  . $SCRIPTS_DIR/volume.sh
  sleep 0.1;
done > $PANEL_FIFO &

# wifi
while true;
do
  . $SCRIPTS_DIR/network.sh
  sleep 10;
done > $PANEL_FIFO &

. panel_colors

panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -f "$PANEL_ICON_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
