#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc rule -a 'Pavucontrol' state=floating
bspc rule -a 'Wicd-client.py' state=floating
bspc rule -a 'Main.py:guake' state=floating focus=on sticky=on


feh --bg-center --bg-fill ~/dotfiles/files/bg.png


panel &
compton &
guake &
