require('mini.ai').setup()
require('mini.comment').setup()
require('mini.jump').setup()
require('mini.pairs').setup()
require('mini.sessions').setup()
require('mini.statusline').setup()
require('mini.surround').setup()
require('mini.tabline').setup()
